WebBudget/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebBudget.Models
{
    public class Item
    {
        public int Id { get; set; }

        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        public decimal Amount { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public int CategoryId { get; set; }
        public bool Exclude { get; set; }
        public int Source { get; set; }

        public string SourceName
        {
            get
            {
                string result = ((Enums.Source)Source).ToString();
                return result;
            }
        }

        public override string ToString()
        {
            return $" Date {Date} Amount {Amount} " +
                $"Description {Description} CategoryId {CategoryId} " +
                $"Exclude {Exclude} Source {Source}";
        }
    }
}

WebBudget/Controllers/AssignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebBudget.Dal;
using WebBudget.Models;

namespace WebBudget.Controllers
{
    public class AssignController : HomeController
    {

        AssignDal assignDal;
        CategoryDal categoryDal;
        ItemDal itemDal;
        readonly string connectionString;

        public AssignController()
        {
            connectionString = Startup.ConnectionString;
            assignDal = new AssignDal(connectionString);
            categoryDal = new CategoryDal(connectionString);
            itemDal = new ItemDal(connectionString);
        }

        public ActionResult List()
        {
            ViewBag.Categories = categoryDal.GetCategoriesDictionary();
            List<Assign> assigns = assignDal.GetAssigns();
            return View(assigns);
        }

        [HttpGet]
        public ActionResult Create()
        {
            List<SelectListItem> categories = categoryDal.GetCategoriesList();
            ViewBag.Categories = categories;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Assign assign)
        {
            assignDal.CreateAssign(assign);
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            List<SelectListItem> categories = categoryDal.GetCategoriesList();
            ViewBag.Categories = categories;
            Assign assign = assignDal.GetAssign(id);
            return View(assign);
        }

        [HttpPost]
        public ActionResult Edit(Assign assign)
        {
            assignDal.UpdateAssign(assign);
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            ViewBag.Categories = categoryDal.GetCategoriesDictionary();

            Assign assign = assignDal.GetAssign(id);
            return View(assign);
        }

        [HttpPost]
        public ActionResult Delete(Assign assign)
        {
            Assign fullAssign = assignDal.GetAssign(assign.Id);
            assignDal.DeleteAssign(fullAssign);
            return RedirectToAction("List");
        }

        /// <summary>
        /// Create Assign key from specific item
        /// </summary>
        /// <param name="id">Item Id</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult CreateKey(int id)
        {
            Item item = itemDal.GetItem(id);
            Assign assign = new Assign();
            if (item.Description != null)
            {
                assign.KeyString = item.Description;
            }

            List<SelectListItem> categories = categoryDal.GetCategoriesList();
            ViewBag.Categories = categories;

            return View("Create", assign);
        }

    }
}

WebBudget/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using WebBudget.Models;
using WebBudget.Dal;
using CsvHelper;

namespace WebBudget.Controllers
{
    public class ItemController : HomeController
    {

        ItemDal itemDal;
        CategoryDal categoryDal;
        AssignDal assignDal;
        RecurringItemDal recurringItemDal;
        LogDal logDal;
        readonly string connectionString;

        public ItemController()
        {
            connectionString = Startup.ConnectionString;
            itemDal = new ItemDal(connectionString);
            categoryDal = new CategoryDal(connectionString);
            assignDal = new AssignDal(connectionString);
            recurringItemDal = new RecurringItemDal(connectionString);
            logDal = new LogDal(connectionString);
        }

        [HttpGet]
        public ActionResult List()
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }

            ViewBag.Categories = categoryDal.GetCategoriesDictionary();

            DateTime startDate = DateTimeExt.FirstDayOfMonth(DateTime.Now);
            DateTime endDate = DateTimeExt.LastDayOfMonth(DateTime.Now);
            SearchByDate searchByDate = new SearchByDate(startDate, endDate);
            ViewBag.SearchByDate = searchByDate;

            //List<Item> items = itemDal.GetItemsByCategory();
            List<Item> items = itemDal.GetItemsByDateCategory(searchByDate);
            return View(items);
        }

        [HttpGet]
        public ActionResult ListDetail()
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }
            ViewBag.Categories = categoryDal.GetCategoriesDictionary();
            List<Item> items = itemDal.GetItems();
            return View(items);
        }

        [HttpGet]
        public ActionResult ListUnassigned()
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }
            ViewBag.Categories = categoryDal.GetCategoriesDictionary();
            List<Item> items = itemDal.GetUnassignedItems();
            return View(items);
        }

        [HttpPost]
        public ActionResult ListByDate(DateTime startDate, DateTime endDate)
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }
            ViewBag.Categories = categoryDal.GetCategoriesDictionary();

            //set default values if not set in parameters
            if (startDate == DateTime.MinValue)
            {
                startDate = DateTimeExt.FirstDayOfMonth(DateTime.Now);
            }
            if (endDate == DateTime.MinValue)
            {
                endDate = DateTimeExt.LastDayOfMonth(DateTime.Now);
            }

            SearchByDate searchByDate = new SearchByDate(startDate, endDate);
            ViewBag.SearchByDate = searchByDate;

            List<Item> items = itemDal.GetItemsByDateCategory(searchByDate);
            return View("List", items);
        }

        [HttpGet]
        public ActionResult Create()
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }
            ViewBag.Categories = categoryDal.GetCategoriesList();
            Item item = new Item();
            return View(item);
        }

        [HttpPost]
        public ActionResult Create(Item item)
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }
            itemDal.CreateItem(item);
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }
            ViewBag.Categories = categoryDal.GetCategoriesList();
            Item item = itemDal.GetItem(id);
            return View(item);
        }

        [HttpPost]
        public ActionResult Edit(Item item)
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }
            itemDal.UpdateItem(item);
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }
            ViewBag.Categories = categoryDal.GetCategoriesDictionary();
            Item item = itemDal.GetItem(id);
            return View(item);
        }

        [HttpPost]
        public ActionResult Delete(Item item)
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }
            Item fullItem = itemDal.GetItem(item.Id);
            itemDal.DeleteItem(fullItem);
            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult Upload()
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }

            List<SelectListItem> sourceList = Enums.SourceList();
            ViewBag.SourceList = sourceList;
            return View("Upload");

        }

        [HttpPost]
        public ActionResult Upload(IFormFile file, int sourceId)
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }

            itemDal.SessionId = CurrentSessionId;

            int itemsRead = 0;
            int itemsCreated = 0;

            List<Item> items = new List<Item>();

            StreamReader streamReader = new StreamReader(file.OpenReadStream());
            CsvReader csv = new CsvReader(streamReader);
            csv.Configuration.HasHeaderRecord = true;

            while (csv.Read())
            {
                List<string> columns = new List<string>();

                for (int i = 0; i < 12; i++)
                {
                    if (csv.TryGetField(i, out string stringField))
                    {
                        columns.Add(stringField);
                    }
                    else
                    {
                        columns.Add(string.Empty);
                    }
                }

                Item item = ConvertLineToRecord(columns, sourceId);

                AssignCategory(item);

                items.Add(item);

                itemsRead++;
            }

            foreach (Item item in items)
            {
                if (item != null && itemDal.IsDuplicate(item) == false)
                {
                    if (itemDal.CreateItem(item))
                    {
                        itemsCreated++;
                    }
                }
            }

            //log upload
            string message = $"Info(15): Upload for {Enums.SourceString(sourceId)} --- ";
            message += $"Records read: {itemsRead} --- ";
            message += $"Records created: {itemsCreated} ";
            Log log = new Log(message)
            {
                SessionId = CurrentSessionId
            };
            logDal.WriteLog(log);

            return RedirectToAction("List", "Item", null);
        }

        /// <summary>
        /// For each item that has no category assigned, 
        /// try to assign one.
        /// </summary>
        /// <returns></returns>
        public ActionResult ApplyCategory()
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }

            List<Item> items = itemDal.GetItems();

            foreach (Item item in items)
            {
                if (item.CategoryId == 0)
                {
                    bool result = AssignCategory(item);
                    if (result)
                    {
                        itemDal.UpdateItem(item);
                    }
                }
            }
            return RedirectToAction("ListUnassigned");
        }

        /// <summary>
        /// For each recurring item, create entries in the item
        /// table if they don't exits. 
        /// </summary>
        /// <returns></returns>
        public ActionResult ApplyRecurring()
        {
            if (!base.IsAuthenticated)
            {
                return RedirectToAction("Login", "Login");
            }

            List<RecurringItem> recurringItems = recurringItemDal.GetRecurringItems();

            foreach (RecurringItem recurringItem in recurringItems)
            {
                CreateRecurring(recurringItem);
            }
            return RedirectToAction("List");
        }

        public ActionResult ListPattern()
        {
            // dictionary to get from category to position
            // key = position, value = categoryID
            Dictionary<int, int> positions = new Dictionary<int, int>();

            // also a dictionary of categories
            // key = categoryId, vlaue = cartgroey object
            Dictionary<int, Category> categories = categoryDal.GetCategoriesDictionary();

            HashSet<DateTime> monthHash = new HashSet<DateTime>();
            Patterns patterns = new Patterns();

            List<Pattern> items = itemDal.GetFilteredPatterns();
            foreach(Pattern item in items)
            {
                Pattern pattern = new Pattern();
                pattern.CategoryId = item.CategoryId;
                pattern.Position = item.Position;

WebBudget/Views/Item/Create.cshtml
@model WebBudget.Models.Item

@{
    ViewData["Title"] = "Create";
    List<SelectListItem> categories = ViewBag.Categories;
    List<SelectListItem> sources = Enums.SourceList();
}

<h2>Create</h2>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" value="@DateTime.MinValue" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" asp-items="@categories" class="form-control">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Exclude" /> @Html.DisplayNameFor(model => model.Exclude)
                    </label>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Source" class="control-label"></label>
                <select asp-for="Source" asp-items="@sources" class="form-control">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="Source" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebBudget/Views/Item/Delete.cshtml
@model WebBudget.Models.Item

@{
    ViewData["Title"] = "Delete";
    Dictionary<int, Category> categories = ViewBag.Categories;
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd>
            @categories[Model.CategoryId].Description
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Exclude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Exclude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SourceName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SourceName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="List">Back to List</a>
    </form>
</div>

WebBudget/Views/Item/Edit.cshtml
@model WebBudget.Models.Item

@{
    ViewData["Title"] = "Edit";
    List<SelectListItem> categories = ViewBag.Categories;
    List<SelectListItem> sources = Enums.SourceList();
}

<h2>Edit</h2>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                @Html.DisplayFor(model => model.Id)
            </div>

            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>

            <div class="form-group">

                <label asp-for="CategoryId" class="control-label">Category</label>
                <select asp-for="CategoryId" asp-items="@categories" class="form-control">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Exclude" /> @Html.DisplayNameFor(model => model.Exclude)
                    </label>
                </div>
            </div>


            <div class="form-group">
                <label asp-for="Source" class="control-label"></label>
                <select asp-for="Source" asp-items="@sources" class="form-control">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="Source" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebBudget/Views/Item/List.cshtml
@model IEnumerable<WebBudget.Models.Item>

@{
    ViewData["Title"] = "List";
    Dictionary<int, Category> categories = ViewBag.Categories;
    SearchByDate searchByDate = ViewBag.SearchByDate;
    DateTime startDate = searchByDate.StartDate;
    DateTime endDate = searchByDate.EndDate;

    int categoryTracker = 0;
    decimal typeSum = 0.0M;
    decimal total = 0.0M;
    decimal creditTotal = 0.0M;
    decimal debitTotal = 0.0M;
    decimal netTotal = 0.0M;
    decimal itemSum = 0.0M;
}

<h2>List</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-action="ListByDate">
    <div class="container">

        <div class="row">
            <div class="col-sm-3">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="control-label">Start Date</label>
                    <input type="date" name="startDate" class="form-control" value="@startDate.Date" />
                </div>
            </div>

            <div class="col-sm-3">
                <div class="form-group">
                    <label class="control-label">End Date</label>
                    <input type="date" name="endDate" class="form-control" value="@endDate.Date" />
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3">
                <div class="form-group">
                    <input type="submit" value="Search" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>

</form>

<div>
    <p>Showing items for dates from @startDate.ToShortDateString() to @endDate.ToShortDateString()</p>
    <p>Not showing excluded items</p>
</div>
<hr />
<hr />

<table class="table">
    <thead>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Note)
            </th>

            <th>
                Category
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Exclude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Source)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            if (categoryTracker != item.CategoryId)
            {
                <tr>
                    <td>--</td>
                    <td>--</td>
                    <td>--</td>
                    <td>--</td>
                    <td>--</td>
                    <td>--</td>
                    <td>--</td>
                    <td>--</td>
                </tr>
                categoryTracker = item.CategoryId;
            }
                <tr>
                    <td>
                        @item.Date.ToShortDateString()
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Note)
                    </td>

                    <td>
                        @categories[item.CategoryId].Description
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Exclude)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.SourceName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                        @Html.ActionLink("Create Key", "CreateKey", "Assign", new { id = item.Id }, null)

                    </td>
                </tr>
            { itemSum += item.Amount; }

        }

        <tr>
            <td>Total</td>
            <td>@itemSum.ToString("C")</td>
            <td>--</td>
            <td>--</td>
            <td>--</td>
            <td>--</td>
            <td>--</td>
            <td>--</td>
            <td>--</td>
        </tr>

    </tbody>
</table>

@{ categoryTracker = 0;}

<table class="table">
    <thead>
        <tr>
            <td align="right"><strong>Category</strong></td>
            <td align="right"><strong>Category Id</strong></td>
            <td align="right"><strong>Amount</strong></td>
            <td align="right"><strong>Target</strong></td>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            if (categoryTracker != item.CategoryId)
            {
                if (typeSum > 0)
                {
                    <tr>
                        @{ string sumToString = typeSum.ToString("C");}
                        <td align="right">@categories[categoryTracker].Description</td>
                        <td align="right">@categoryTracker</td>
                        <td align="right">@sumToString</td>
                        <td align="right">@categories[categoryTracker].Target.ToString("C")</td>

                    </tr>
                }

                categoryTracker = item.CategoryId;
                typeSum = 0;
            }
            typeSum += item.Amount;
            total += item.Amount;

            // if this is a debit
            if (categories[item.CategoryId].IsDebit)
            {
                netTotal += item.Amount;
                debitTotal += item.Amount;
            }
            else
            {
                netTotal -= item.Amount;
                creditTotal += item.Amount;
            }
        }

        <!-- last category-->
        @{if (typeSum > 0)
            {
                <tr>
                    @{ string sumToString2 = typeSum.ToString("C");}
                    <td align="right">@categories[categoryTracker].Description</td>
                    <td align="right">@categoryTracker</td>
                    <td align="right">@sumToString2</td>
                    <td align="right">@categories[categoryTracker].Target.ToString("C")</td>

                </tr>
            }
        }

        <tr>
            <td align="right">--------</td>
            <td align="right">--------</td>
            <td align="right">--------</td>
        </tr>

        <tr>
            @{ string totalToString = total.ToString("C");}
            <td align="right">Total of Items</td>
            <td align="right">@totalToString</td>
            <td align="right"> </td>
        </tr>
        <tr>
            @{ string creditTotalToString = creditTotal.ToString("C");}
            <td align="right">Credit Total</td>
            <td align="right">@creditTotalToString</td>
            <td align="right"> </td>
        </tr>
        <tr>
            @{ string debitTotalToString = debitTotal.ToString("C");}
            <td align="right">Debit Total</td>
            <td align="right">@debitTotalToString</td>
            <td align="right"> </td>
        </tr>
        <tr>
            @{ string netTotalToString = netTotal.ToString("C");}
            <td align="right">Net Total</td>
            <td align="right">@netTotalToString</td>
            <td align="right"> </td>
        </tr>


    </tbody>

</table>

WebBudget/Views/Item/ListUnassigned.cshtml
@model IEnumerable<WebBudget.Models.Item>

    @{
        ViewData["Title"] = "List";
        Dictionary<int, Category> categories = ViewBag.Categories;
    }

    <h2>List Unassigned</h2>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <div>
        <p>Showing unassigned items</p>
    </div>
    <hr />
    <hr />

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Amount)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Note)
                </th>

                <th>
                    Category
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Exclude)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Source)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @item.Date.ToShortDateString()
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>

                <td>
                    @categories[item.CategoryId].Description
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Exclude)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.SourceName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                    @Html.ActionLink("Create Key", "CreateKey", "Assign", new { id = item.Id }, null)

                </td>
            </tr>
            }
        </tbody>
    </table>